### PR TITLE
Replaced Imagefile struct with image.RGBA

### LINKED ISSUE #8: Use image/RGBA
https://golang.org/pkg/image/#RGBA
This would allow us to remove some code.

### PR DESCRIPTION
**Pull request by peterhellberg**
Fixes #8

### CODE REVIEW

**Comment by peterhellberg** [comment]
I’ve also written a small Imagefile viewer using Ebiten:
<https://gist.github.com/peterhellberg/c82af50ac994c40f174b>

displaying gopher.image.bz2

**Comment by peterhellberg** [comment]
I have some formatting changes in encode.go (and a comment). Should I open a new PR for this or just push it to this branch?

**Comment by mehlon** [comment]
Open a new PR. I also believe we can write [the pixels in encode.go](https://github.com/mehlon/imagefile/blob/master/encode.go#L34-L45) directly to the writer, without any big endian conversion.

**Comment by opennota** [comment]
> I also believe we can write the pixels in encode.go

http://andrew.yurisich.com/work/2014/07/16/dont-link-that-line-number/

**Comment by mehlon** [comment]
Oh right, thanks!

**Pull request merged**
