### PR TITLE
Make the implementation suck less; add command-line tools

### PR DESCRIPTION
**Pull request by opennota**
Written from scratch because mehlon/imagefile didn't use image.RGBA.Pix

### CODE REVIEW

**Comment by mehlon** [comment]
Thank you.

**Comment by peterhellberg** [comment]
This is indeed a very good PR, made the code suck way less :+1:

Should *script* in .travis.yml be changed to `go test -v .` since the command line tools are “tested” by compiling them?

**Comment by opennota** [comment]
> Should script in .travis.yml be changed to go test -v . since the command line tools are “tested” by compiling them?

The tests for the command-line tools can be added later. Maybe I'll write them on my holiday.

**Comment by peterhellberg** [comment]
The `FormatError` type was used to match the [jpeg](https://golang.org/pkg/image/jpeg/#FormatError) and [png](https://golang.org/pkg/image/png/#FormatError) packages, did you have a reason to remove it?

**Comment by opennota** [comment]
My bad. I think it should be brought back and replace the `ErrNoMagic`. The latter is also used in the tests and they should be corrected, too.

**Comment by peterhellberg** [comment]
Ok, I’ll add them back in a PR soon

**Pull request merged**
